"""
Django settings for jsg project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7vq=89q*a_keq3h=*7&$s*t_q6f6$bm5+zqt22^g2+k+wcl_4*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    # 'simplepro',
    # 'simpleui',
    # 'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'tables',
    'query',
    'uploads',
    'corsheaders',
    # 'guardian',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'simplepro.middlewares.SimpleMiddleware'
]

# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.ModelBackend', # default
#     # 'guardian.backends.ObjectPermissionBackend',
# )

ROOT_URLCONF = 'jsg.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jsg.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        # 'NAME': 'cnki_2001_iser_pro',
        # 'USER': 'postgres',
        # 'PASSWORD': 'cnki.P@$$w0rd',
        # 'HOST': '10.90.64.229',
        # 'PORT': '5432',
        'NAME': 'cnki_2001_jsg_pro',
        'USER': 'postgres',
        'PASSWORD': 'cnki5722902',
        'HOST': '192.168.105.28',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #      # 验证密码和用户名相似度
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        # 验证密码最少长度
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        # 'OPTIONS': {
        #     'min_length': 9,
        # }
    },
    # {
    #     # 密码是否出现在常用密码中
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    {
        # 密码不能全是数字
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'media')
)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 即项目路径下的media文件夹，没有则自动创建
MEDIA_URL = '/media/'  # 这个是在浏览器上访问该上传文件的url的前缀

APPEND_SLASH = False

# 跨域问题
CORS_ORIGIN_ALLOW_ALL = True

REST_FRAMEWORK = {
    # 新增的
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     'login.auth.ExpiringTokenAuthentication',   # 根据自己的实际情况填写路径
    # ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
}

# 停用词路径
STOP_WORD_PATHS = os.path.join(BASE_DIR, 'login')

# 定时任务
# '*/1 * * * *'每一分钟执行一次
# '10 12 * * *'12点10分执行
CRONJOBS = [
    ('0 4 * * *', 'login.cron.cron.create_hotword', '>> /www/govin/logs/crontab.log'),
]

PUN_LIST = [
    '。', '，', '、', '？', '！', '；', '：', '“', '”', '‘', '’', '「', '」', '『', '』', '（', '）', '[', ']',

    '〔', '〕', '【', '】', '——', '—', '……', '…', '—', '-', '～', '·', '《', '》', '〈', '〉', '﹏﹏', '___',

    '.',
]

CLUE_KEYWORDS_LIST = [
    "总之", "总而言之", "报导", "新华社", "报道", "定金",
]

HOPE_KEYWORDS_LIST = [
    "恭请", "请求领导", "紧急求助", "要严查", "公正的答复", "协助我们", "希望政府", "保证我们", "我们希望", "我们恳求", "诚心恳请",
    "希望", "我期待", "请省长", "请市长", "还希望", "能不能", "是否可以", "恳请领导", "希望领导", "希望",
]


SIMPLEPRO_INFO = False
# SIMPLEUI_HOME_PAGE = 'https://www.sunwu.zone'
SIMPLEUI_ICON = {
    '成果信息表': 'fas fa-user-tie',
    '表': 'fab fa-docker',
    '日志记录': 'fas fa-flask',
    '认证令牌': 'fas fa-fingerprint',
    '令牌': 'fas fa-fingerprint',

    '课题信息表': 'fas fa-book-open',

    '研究人员信息表': 'fas fa-graduation-cap',

    '热词表': 'fas fa-fire-alt',

    '敏感词表': 'fas fa-skull-crossbones',

}

# 让 Django 用户认证系统使用自定义的用户模型
AUTH_USER_MODEL = 'tables.User'

PROJECTS_STATUS_CHOICE = {0: '不显示', 1: '合格', 2: '待完善', 3: '检测中', 4: '不合格', 5: '删除'}
RESEARCH_STATUS_CHOICE = {0: '未开启', 1: '招标中', 2: '推进中', 3: '已结题', 4: '删除'}
BIDDER_STATUS_CHOICE = {0: '暂存', 1: '投标中', 2: '中标', 3: '未中标', 4: '删除'}
BIDDER_CONCLUSION_STATUS = {0: '未开始', 1: '审批中', 2: '已通过', 3: '未通过'}
PRO_RELATIONS_ROLES = {1: '组长', 2: '副组长', 3: '组员'}

ORG_NATURE_LOWER_LEVEL = 4
ORG_NATURE_HIGHER_LEVEL = 1
ORG_GROUP_LOWER_LEVEL = 4
ORG_GROUP_SUPERUSER_LEVEL = 1
ORG_GROUP_MANAGER_LEVEL = 2

# 组长副组长组员三个角色分别对应的分数
ROLES_NAME = {"组长": 1, "副组长": 2, "组员": 3}
ROLES_SCORE = {1: 1.2, 2: 1.1, 3: 1}
