# Generated by Django 3.0.5 on 2020-07-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20200629_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='back_is_login',
            field=models.BooleanField(default=0, verbose_name='判断后台是否登录'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pts', to='tables.Organization', verbose_name='现所属单位'),
        ),
    ]
