# Generated by Django 3.0.5 on 2020-07-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20200706_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='warn', max_length=10, verbose_name='级别')),
                ('address', models.CharField(max_length=100, verbose_name='追踪路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('user', models.IntegerField(null=True, verbose_name='用户ID')),
                ('keyword', models.TextField(verbose_name='提示关键词')),
            ],
            options={
                'verbose_name_plural': '程序运行警告报错信息表',
            },
        ),
    ]
