# Generated by Django 3.0.5 on 2020-09-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_organization_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='release_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='变动时间'),
        ),
    ]
