# Generated by Django 3.0.5 on 2020-09-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_projects_release_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgnature',
            name='ord_by',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
    ]
