# Generated by Django 3.0.5 on 2020-10-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20200923_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='competent_dpt',
            field=models.IntegerField(default=0, verbose_name='主管部门'),
        ),
        migrations.AddField(
            model_name='organization',
            name='superior_unit',
            field=models.IntegerField(default=0, verbose_name='上级单位'),
        ),
    ]
