# Generated by Django 3.0.5 on 2020-10-16 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20201014_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.IntegerField(verbose_name='角色')),
                ('id_card_code', models.CharField(max_length=18, null=True, verbose_name='社会信用码/身份证号')),
                ('unit_name', models.CharField(max_length=100, null=True, verbose_name='单位名称')),
                ('unit_contacts', models.CharField(max_length=100, null=True, verbose_name='单位联系人')),
                ('cell_phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('login_pwd', models.CharField(max_length=10, verbose_name='登录密码')),
                ('certification_materials', models.FileField(null=True, upload_to='', verbose_name='证明材料')),
                ('business_license', models.FileField(null=True, upload_to='', verbose_name='营业执照')),
                ('verification_code_photo', models.ImageField(null=True, upload_to='', verbose_name='验证码图片')),
                ('verification_code', models.CharField(max_length=5, null=True, verbose_name='验证码')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('unit_nature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Classify', verbose_name='单位属性')),
            ],
            options={
                'verbose_name': '注册表',
                'verbose_name_plural': '注册表',
            },
        ),
    ]
