# Generated by Django 3.0.5 on 2020-10-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='business_license',
            field=models.FileField(null=True, upload_to='register/business_license/%Y/%m', verbose_name='营业执照'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='certification_materials',
            field=models.FileField(null=True, upload_to='register/certification_materials/%Y/%m', verbose_name='证明材料'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='verification_code_photo',
            field=models.ImageField(null=True, upload_to='register/verification_code/%Y/%m', verbose_name='验证码图片'),
        ),
    ]
