# Generated by Django 3.0.5 on 2020-10-26 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0013_auto_20201020_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_a',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_b',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_attached',
            field=models.FileField(null=True, upload_to='bid/%Y/%m', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='bid',
            name='conclusion_attached',
            field=models.FileField(null=True, upload_to='bid/%Y/%m', verbose_name='结题报告'),
        ),
        migrations.AddField(
            model_name='bid',
            name='interim_attached',
            field=models.FileField(null=True, upload_to='bid/%Y/%m', verbose_name='中期报告'),
        ),
        migrations.AddField(
            model_name='bid',
            name='interim_status',
            field=models.IntegerField(choices=[(0, '暂存'), (1, '投标中'), (2, '初审通过'), (3, '初审驳回'), (4, '删除'), (5, '中标'), (6, '立项驳回')], default=0, verbose_name='中期评审状态'),
        ),
        migrations.AddField(
            model_name='participant',
            name='cell_phone',
            field=models.CharField(max_length=18, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='participant',
            name='research_direction',
            field=models.CharField(max_length=100, null=True, verbose_name='研究方向'),
        ),
        migrations.AddField(
            model_name='user',
            name='cell_phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Participant', verbose_name='人员关联'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder_status',
            field=models.IntegerField(choices=[(0, '暂存'), (1, '投标中'), (2, '初审通过'), (3, '初审驳回'), (4, '删除'), (5, '中标'), (6, '立项驳回')], default=0, verbose_name='投标状态'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='conclusion_status',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '审批中'), (2, '已通过'), (3, '已驳回'), (4, '待提交')], default=0, verbose_name='结题状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.CharField(max_length=18, null=True, verbose_name='社会信用码/身份证号'),
        ),
        migrations.CreateModel(
            name='BidEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(default='无', max_length=10, verbose_name='评审结果')),
                ('stage', models.CharField(default='初审', max_length=10, verbose_name='阶段')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('evaluate_attached', models.FileField(null=True, upload_to='bid_evaluation/%Y/%m', verbose_name='附件')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('designated_experts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Participant', verbose_name='指定专家')),
                ('operate_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作账号')),
                ('relate_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Bid', verbose_name='对应投标')),
            ],
            options={
                'verbose_name': '课题评审表-针对投标小课题',
            },
        ),
    ]
