# Generated by Django 3.0.5 on 2020-10-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_auto_20201026_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='info_status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
