# Generated by Django 3.0.5 on 2020-10-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_userregister_info_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='business_license',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='unit_contacts',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='unit_name',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='unit_nature',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=300, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_license',
            field=models.FileField(null=True, upload_to='organizations/license/', verbose_name='营业执照'),
        ),
        migrations.AddField(
            model_name='organization',
            name='certification_materials',
            field=models.FileField(null=True, upload_to='organizations/materials/', verbose_name='证明材料'),
        ),
        migrations.AddField(
            model_name='organization',
            name='id_card_code',
            field=models.CharField(max_length=18, null=True, verbose_name='社会信用码'),
        ),
        migrations.AddField(
            model_name='organization',
            name='postcode',
            field=models.IntegerField(null=True, verbose_name='邮政编码'),
        ),
        migrations.AddField(
            model_name='organization',
            name='register_capital',
            field=models.FloatField(null=True, verbose_name='注册资本'),
        ),
        migrations.AddField(
            model_name='organization',
            name='register_date',
            field=models.DateField(null=True, verbose_name='注册时间'),
        ),
        migrations.AddField(
            model_name='organization',
            name='register_type',
            field=models.CharField(max_length=100, null=True, verbose_name='注册类型'),
        ),
        migrations.AddField(
            model_name='organization',
            name='unit_fax',
            field=models.CharField(max_length=20, null=True, verbose_name='单位传真'),
        ),
        migrations.AddField(
            model_name='organization',
            name='unit_tel',
            field=models.CharField(max_length=20, null=True, verbose_name='单位电话'),
        ),
        migrations.AddField(
            model_name='userregister',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='photo',
            field=models.ImageField(null=True, upload_to='organizations/logo/', verbose_name='单位logo'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='certification_materials',
            field=models.FileField(null=True, upload_to='register/materials/%Y/%m', verbose_name='证明材料'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='verification_code_photo',
            field=models.ImageField(null=True, upload_to='register/verify_code/%Y/%m', verbose_name='验证码图片'),
        ),
    ]
