# Generated by Django 3.0.5 on 2020-11-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0018_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certification_materials',
            field=models.CharField(max_length=100, null=True, verbose_name='证明材料'),
        ),
    ]
