# Generated by Django 3.0.5 on 2020-11-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0019_user_certification_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='remarks',
            field=models.CharField(max_length=200, null=True, verbose_name='备注'),
        ),
    ]
