# Generated by Django 3.0.5 on 2020-11-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0020_userregister_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='pro_source',
            field=models.CharField(default='iser', max_length=10, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, verbose_name='机构名称'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
    ]
