# Generated by Django 3.0.5 on 2020-11-11 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_projects_org_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='academic_degree',
            field=models.CharField(max_length=100, null=True, verbose_name='本人学位'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.TextField(null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='education',
            field=models.CharField(max_length=100, null=True, verbose_name='本人最高学历'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='photo',
            field=models.ImageField(null=True, upload_to='participants/portrait/', verbose_name='头像'),
        ),
        migrations.CreateModel(
            name='UserToParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('birth', models.DateField(null=True, verbose_name='出生日期')),
                ('education', models.CharField(max_length=100, null=True, verbose_name='本人最高学历')),
                ('academic_degree', models.CharField(max_length=100, null=True, verbose_name='本人学位')),
                ('address', models.TextField(null=True, verbose_name='地址')),
                ('postcode', models.IntegerField(null=True, verbose_name='邮编')),
                ('brief', models.TextField(null=True, verbose_name='简介')),
                ('research_direction', models.CharField(max_length=100, null=True, verbose_name='专长')),
                ('photo', models.ImageField(null=True, upload_to='participants/portrait/', verbose_name='头像')),
                ('id_card_photo_positive', models.ImageField(null=True, upload_to='participants/id_card/', verbose_name='身份证正面')),
                ('id_card_photo_reverse', models.ImageField(null=True, upload_to='participants/id_card/', verbose_name='身份证反面')),
                ('job_certi', models.ImageField(null=True, upload_to='participants/job_certi/', verbose_name='在职证明')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('approval_date', models.DateTimeField(null=True, verbose_name='审批时间')),
                ('up_status', models.IntegerField(default=0, verbose_name='状态')),
                ('user', models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '研究人员验证表',
            },
        ),
    ]
