# Generated by Django 3.0.5 on 2020-11-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0023_auto_20201111_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoparticipant',
            name='remarks',
            field=models.TextField(null=True, verbose_name='审批备注'),
        ),
        migrations.AlterField(
            model_name='usertoparticipant',
            name='job_certi',
            field=models.FileField(null=True, upload_to='participants/job_certi/', verbose_name='在职证明'),
        ),
    ]
