# Generated by Django 3.0.5 on 2020-11-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0024_auto_20201111_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='id_card_photo_positive',
            field=models.ImageField(null=True, upload_to='participants/id_card/', verbose_name='身份证正面'),
        ),
        migrations.AddField(
            model_name='participant',
            name='id_card_photo_reverse',
            field=models.ImageField(null=True, upload_to='participants/id_card/', verbose_name='身份证反面'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='user/portrait/', verbose_name='头像'),
        ),
    ]
