# Generated by Django 3.0.5 on 2020-11-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0026_remove_organization_competent_dpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='level',
            field=models.IntegerField(default=1, verbose_name='vip级别'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='business_license',
            field=models.FileField(null=True, upload_to='organizations/license/%Y/%m', verbose_name='营业执照'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='certification_materials',
            field=models.FileField(null=True, upload_to='organizations/materials/%Y/%m', verbose_name='证明材料'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='photo',
            field=models.ImageField(null=True, upload_to='organizations/logo/%Y/%m', verbose_name='单位logo'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id_card_photo_positive',
            field=models.ImageField(null=True, upload_to='participants/id_card/%Y/%m', verbose_name='身份证正面'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id_card_photo_reverse',
            field=models.ImageField(null=True, upload_to='participants/id_card/%Y/%m', verbose_name='身份证反面'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='photo',
            field=models.ImageField(null=True, upload_to='participants/portrait/%Y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='user/portrait/%Y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='usertoparticipant',
            name='id_card_photo_positive',
            field=models.ImageField(null=True, upload_to='participants/id_card/%Y/%m', verbose_name='身份证正面'),
        ),
        migrations.AlterField(
            model_name='usertoparticipant',
            name='id_card_photo_reverse',
            field=models.ImageField(null=True, upload_to='participants/id_card/%Y/%m', verbose_name='身份证反面'),
        ),
        migrations.AlterField(
            model_name='usertoparticipant',
            name='job_certi',
            field=models.FileField(null=True, upload_to='participants/job_certi/%Y/%m', verbose_name='在职证明'),
        ),
        migrations.AlterField(
            model_name='usertoparticipant',
            name='photo',
            field=models.ImageField(null=True, upload_to='participants/portrait/%Y/%m', verbose_name='头像'),
        ),
        migrations.CreateModel(
            name='ParToVIP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=2, verbose_name='vip级别')),
                ('result', models.IntegerField(default=0, verbose_name='结果')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('approval_date', models.DateTimeField(null=True, verbose_name='审批时间')),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Participant', verbose_name='研究人员')),
            ],
            options={
                'verbose_name_plural': '研究人员升级专家vip认证表',
            },
        ),
        migrations.CreateModel(
            name='ParRePro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('support_materials', models.FileField(null=True, upload_to='participants/tovip/%Y/%m', verbose_name='证明材料')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Participant', verbose_name='研究人员')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Projects', verbose_name='成果')),
            ],
            options={
                'verbose_name_plural': '研究人员认证成果表',
            },
        ),
    ]
