# Generated by Django 3.0.5 on 2020-11-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0027_auto_20201117_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_con_date',
            field=models.DateTimeField(null=True, verbose_name='结题时间'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_interim_date',
            field=models.DateTimeField(null=True, verbose_name='中期评审时间'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_lix_date',
            field=models.DateTimeField(null=True, verbose_name='立项时间'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_trial_date',
            field=models.DateTimeField(null=True, verbose_name='初审时间'),
        ),
        migrations.AddField(
            model_name='research',
            name='con_date',
            field=models.DateField(null=True, verbose_name='结题时间'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder_status',
            field=models.IntegerField(choices=[(0, '暂存'), (1, '投标中'), (2, '初审通过'), (3, '初审驳回'), (4, '删除'), (5, '立项中标'), (6, '立项驳回')], default=0, verbose_name='投标状态'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='interim_status',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '审批中'), (2, '已通过'), (3, '已驳回'), (4, '待提交')], default=0, verbose_name='中期评审状态'),
        ),
        migrations.AlterField(
            model_name='parrepro',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='uuid',
            field=models.CharField(max_length=50, unique=True, verbose_name='唯一标识'),
        ),
    ]
