# Generated by Django 3.0.5 on 2020-11-25 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0028_auto_20201120_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_trial_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_trial_user', to=settings.AUTH_USER_MODEL, verbose_name='初审用户'),
        ),
        migrations.AddField(
            model_name='bidevaluation',
            name='is_show',
            field=models.BooleanField(default=1, verbose_name='是否显示'),
        ),
        migrations.AddField(
            model_name='bidevaluation',
            name='operate_time',
            field=models.DateTimeField(null=True, verbose_name='专家操作时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户'),
        ),
        migrations.AlterField(
            model_name='bidevaluation',
            name='result',
            field=models.IntegerField(default=0, verbose_name='评审结果'),
        ),
        migrations.AlterField(
            model_name='bidevaluation',
            name='stage',
            field=models.CharField(default='立项', max_length=10, verbose_name='阶段'),
        ),
    ]
